### ISSUE TITLE
Plus/Minus mutator for variables

### ISSUE THREAD

**Issue by T94T** [OpenRoberta/blockly#26]
Hi,
First of all many thanks for your great implementation of blockly. I'm interested in having your variable handling in my application. Also, the if-then-else block with the +/- icons are much easier to use than the original.
Can anybody please give me some hints on how to implement this functionality in a "plain" google blockly setup?
I noticed it has to do something with the mutatorMinus.js and mutatorPlus.js files.
Thanks a lot for your feedbak!

![blocklyaddremove](https://user-images.githubusercontent.com/17198363/27037493-6e0a2560-4f88-11e7-9855-c26ac8b8d7d6.png)

**Comment by bjost2s** [comment]
You are absolutely right, you need at least the two mutatorMinus/Plus files and make them available in block.js. After that you can create new blocks with these new mutators. A good example is our if block in the logic.js file at the end: robControls_if . You have to specify the mutation and update function. The start block in the image above is quite more complicated, because it is not only changing it's own representation but also adds or deletes other blocks, you can see the sources in robControls.js at the beginning.
Please ask, if you need further information.

**Comment by T94T** [comment]
Thank you so much for your input. I was missing the requires in block.js. After that building was working. But, unfortunately the plus icon does not get rendered. Cannot figure out the problem. Hope you can help me again.
![missingmutator](https://user-images.githubusercontent.com/17198363/27778932-8f0b46e4-5fbf-11e7-8f62-2a97971153fe.png)

**Comment by T94T** [comment]
Found it! I had to adapt the block_svg.js file also. Thanks again! This could be closed for now.
